import "./globals.css";
import Nav from "./components/Nav";

export const metadata = {
  title: "Hate Speech Detector",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-purple-700 min-h-screen flex">
          <Nav />
          <div className="bg-white flex-grow mt-2 mr-2 mb-2 rounded-lg p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
